import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { generateText } from "ai";
import type { CoreMessage } from "ai";
import OpenAI from "openai";
import type { CardType } from "./card-templates";
import { getPrompt, getAspectRatio } from "./card-templates";

const google = createGoogleGenerativeAI({
  apiKey: process.env.GEMINI_API_KEY,
});

const GEMINI_MODEL = "gemini-2.5-flash-preview-05-20" as const;
const MAX_IMAGE_BYTES = 3 * 1024 * 1024; // 3MB

export interface GenerateCardInput {
  imageBase64: string;
  cardType: CardType;
}

export interface GenerateCardResult {
  url?: string;
  imageBase64?: string;
  error?: string;
}

// --- Gemini provider ---
async function generateWithGemini(
  buf: Buffer,
  prompt: string,
  aspectRatio: string
): Promise<string> {
  const messages: CoreMessage[] = [
    {
      role: "user",
      content: [
        { type: "image", image: buf, mimeType: "image/jpeg" },
        { type: "text", text: prompt },
      ],
    },
  ];
  const result = await generateText({
    model: google(GEMINI_MODEL),
    messages,
    providerOptions: {
      google: {
        responseModalities: ["IMAGE"],
        imageConfig: { aspectRatio },
      },
    },
  });

  const file = result.files?.[0];
  if (!file?.base64) throw new Error("No image was generated by Gemini");
  return `data:${file.mimeType ?? "image/png"};base64,${file.base64}`;
}

// --- OpenAI fallback provider ---
async function generateWithOpenAI(
  buf: Buffer,
  prompt: string
): Promise<string> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error("OPENAI_API_KEY not configured");

  const openai = new OpenAI({ apiKey, maxRetries: 0 });
  const imageFile = new File([buf], "selfie.jpg", { type: "image/jpeg" });

  const response = await openai.images.edit({
    model: "gpt-image-1",
    image: imageFile,
    prompt,
    size: "1024x1024",
  });

  const b64 = response.data?.[0]?.b64_json;
  if (!b64) throw new Error("No image returned by OpenAI");
  return `data:image/png;base64,${b64}`;
}

// --- Main export ---
export async function generateCard(
  input: GenerateCardInput
): Promise<GenerateCardResult> {
  const { imageBase64, cardType } = input;

  if (!imageBase64 || typeof imageBase64 !== "string") {
    return { error: "Missing or invalid image" };
  }

  const raw = imageBase64.replace(/^data:image\/\w+;base64,/, "");
  const buf = Buffer.from(raw, "base64");
  if (buf.length > MAX_IMAGE_BYTES) {
    return { error: "Image too large (max 3MB)" };
  }

  const prompt = getPrompt(cardType);
  const aspectRatio = getAspectRatio(cardType);

  // Try Gemini first
  try {
    console.log("[generate-card] Trying Gemini...");
    const imageBase64Result = await generateWithGemini(buf, prompt, aspectRatio);
    console.log("[generate-card] Gemini succeeded");
    return { imageBase64: imageBase64Result };
  } catch (geminiErr) {
    const geminiMsg = geminiErr instanceof Error ? geminiErr.message : String(geminiErr);
    console.warn("[generate-card] Gemini failed:", geminiMsg);

    const isQuota =
      geminiMsg.includes("429") ||
      geminiMsg.includes("quota") ||
      geminiMsg.includes("resource_exhausted") ||
      geminiMsg.includes("RESOURCE_EXHAUSTED");

    // Only fall back to OpenAI on quota/rate errors
    if (!isQuota) {
      if (geminiMsg.includes("400") || geminiMsg.includes("invalid_argument")) {
        return { error: "Invalid image or request. Try a different photo." };
      }
      return { error: "Something went wrong: " + geminiMsg.slice(0, 120) };
    }
  }

  // Fallback: OpenAI gpt-image-1
  try {
    console.log("[generate-card] Falling back to OpenAI...");
    const imageBase64Result = await generateWithOpenAI(buf, prompt);
    console.log("[generate-card] OpenAI succeeded");
    return { imageBase64: imageBase64Result };
  } catch (openaiErr) {
    const openaiMsg = openaiErr instanceof Error ? openaiErr.message : String(openaiErr);
    console.error("[generate-card] OpenAI also failed:", openaiMsg);
    return { error: "Something went wrong: " + openaiMsg.slice(0, 120) };
  }
}
